### ISSUE TITLE
PDF-AAM authors: [] block is rendered as "platform API maintainers"

### ISSUE THREAD

**Issue by cookiecrook** [w3c/pdf-aam#1]
PDF-AAM ReSpec `authors: []` block is rendered as "Platform Mapping Maintainers"

Filing the issue to fix it later... Somewhere in ReSpec, presumably.

**Comment by cookiecrook** [comment]
`postProcess: [addPlatformMaintainers],`

**Comment by jnurthen** [comment]
yeah - remove that and it will go back to authors
