### ISSUE TITLE
Add write privs for PDF-AAM to Paul, Zak, and James

### ISSUE THREAD

**Issue by cookiecrook** [w3c/pdf-aam#3]
I can't modify issues in this new repo... Please add the following people:

- @zakkinsey
- @PaulRayius
- @cookiecrook 
 
Ideally, we need the ability to be able to assign issues and PRs, act as reviewers, modify labels, etc. I don't think merge privs are needed yet, but that might make it easier on the other ARIA editors.

**Comment by jnurthen** [comment]
@daniel-montalvo Can you please do this - I have no privs here either

**Comment by daniel-montalvo** [comment]
@zakkinsey
@PaulRayius
@cookiecrook
@jnurthen 
You should all now have write privs. Let me know otherwise.

**Comment by cookiecrook** [comment]
Confirmed. Thanks!
